In [ ]:
# https://www.kaggle.com/mrmorj/restaurant-recommendation-challenge?select=orders.csv
# Which methods for feature selection? (manual, forwrad seleciton, backward selection)
# PCA or feature selection. Which one comes first? lightFM?
# m1 m2 m3 stuffs (3 different approaches?)
#https://www.kaggle.com/fahadsyed97/us-restaurants-post-covid-uncleaned-dataset
#https://www.kaggle.com/yelp-dataset/yelp-dataset?select=yelp_academic_dataset_review.json

In [ ]:
from google.colab import files

upload = files.upload()

Saving items.csv to items.csv

In [ ]:
import pandas as pd

dataframe = pd.read_csv("/content/items.csv")

In [ ]:
dataframe

,address,categories/0,categories/1,categories/2,categories/3,categories/4,categories/5,categories/6,categoryName,cid,...,searchPageUrl,searchString,state,street,subTitle,temporarilyClosed,title,totalScore,url,website
0,"110 Marietta St NW, Atlanta, GA 30303",American restaurant,Restaurant,NaN,NaN,NaN,NaN,NaN,American restaurant,15728115204861440356,...,https://www.google.com/maps/search/restaurant+...,NaN,Georgia,110 Marietta St NW,NaN,False,Glenn's Kitchen,4.4,https://www.google.com/maps/place/Glenn's+Kitc...,http://www.glennskitchenatl.com/
1,"123 Luckie St NW #108, Atlanta, GA 30303",Creole restaurant,Breakfast restaurant,Lunch restaurant,NaN,NaN,NaN,NaN,Creole restaurant,385283237384374756,...,https://www.google.com/maps/search/restaurant+...,NaN,Georgia,123 Luckie St NW #108,NaN,False,The Food Shoppe,4.7,https://www.google.com/maps/place/The+Food+Sho...,http://www.thefoodshoppeatl.com/
2,"678 10th St NW, Atlanta, GA 30318",Restaurant,Asian restaurant,Korean restaurant,Sports bar,NaN,NaN,NaN,Restaurant,3615774370683771613,...,https://www.google.com/maps/search/restaurant+...,NaN,Georgia,678 10th St NW,NaN,False,Pijiu Belly,4.5,https://www.google.com/maps/place/Pijiu+Belly/...,http://pijiubelly.com/
3,"930 Spring St NW, Atlanta, GA 30309",Fast food restaurant,Gift wrap store,Noodle shop,Pasta shop,Restaurant,Salad shop,NaN,Fast food restaurant,4125966856776304985,...,https://www.google.com/maps/search/restaurant+...,NaN,Georgia,930 Spring St NW,NaN,False,Twisted Kitchen - Midtown,4.3,https://www.google.com/maps/place/Twisted+Kitc...,https://www.twistedkitchen.com/
4,"950 W Peachtree St NW #215, Atlanta, GA 30309",New American restaurant,Bar,Beauty salon,Cocktail bar,Wine bar,NaN,NaN,New American restaurant,6866774244082779487,...,https://www.google.com/maps/search/restaurant+...,NaN,Georgia,950 W Peachtree St NW #215,NaN,False,Marlow's Tavern,4.4,https://www.google.com/maps/place/Marlow's+Tav...,http://www.marlowstavern.com/locations/midtown
5,"87 Poplar St NW, Atlanta, GA 30303",Pizza restaurant,Bar,European restaurant,Italian restaurant,Restaurant,NaN,NaN,Pizza restaurant,16554682931154762976,...,https://www.google.com/maps/search/restaurant+...,NaN,Georgia,87 Poplar St NW,NaN,False,Slice Downtown,4.5,https://www.google.com/maps/place/Slice+Downto...,http://sliceatlanta.com/
6,"240 Peachtree St, Atlanta, GA 30303",Fine dining restaurant,Event venue,Live music bar,Restaurant,Seafood restaurant,Steak house,Wine bar,Fine dining restaurant,16224791424951492843,...,https://www.google.com/maps/search/restaurant+...,NaN,Georgia,240 Peachtree St,NaN,False,Ray's In the City,4.5,https://www.google.com/maps/place/Ray's+In+the...,https://www.raysrestaurants.com/raysinthecity/...
7,"133 Luckie St NW, Atlanta, GA 30303",American restaurant,Steak house,NaN,NaN,NaN,NaN,NaN,American restaurant,18104949974782516958,...,https://www.google.com/maps/search/restaurant+...,NaN,Georgia,133 Luckie St NW,NaN,False,Ted's Montana Grill,4.3,https://www.google.com/maps/place/Ted's+Montan...,https://www.tedsmontanagrill.com/tmg001.html
8,"181 Peachtree St, Atlanta, GA 30303",Restaurant,NaN,NaN,NaN,NaN,NaN,NaN,Restaurant,15374394282359327213,...,https://www.google.com/maps/search/restaurant+...,NaN,Georgia,181 Peachtree St,NaN,False,Atlanta Grill,4.5,https://www.google.com/maps/place/Atlanta+Gril...,NaN
9,"300 Marietta St NW, Atlanta, GA 30313",Pizza restaurant,Restaurant,NaN,NaN,NaN,NaN,NaN,Pizza restaurant,7370191735781685119,...,https://www.google.com/maps/search/restaurant+...,NaN,Georgia,300 Marietta St NW,NaN,False,Max's Coal Oven Pizzeria,4.4,https://www.google.com/maps/place/Max's+Coal+O...,http://www.maxsatl.com/

In [ ]:
dataframe.columns

Index(['address', 'categories/0', 'categories/1', 'categories/2',
       'categories/3', 'categories/4', 'categories/5', 'categories/6',
       'categoryName', 'cid', 'city', 'countryCode', 'isAdvertisement',
       'locatedIn', 'location/lat', 'location/lng', 'menu', 'neighborhood',
       'orderBy/0/name', 'orderBy/0/url', 'permanentlyClosed', 'phone',
       'placeId', 'plusCode', 'postalCode', 'price', 'rank', 'reviewsCount',
       'reviewsDistribution/fiveStar', 'reviewsDistribution/fourStar',
       'reviewsDistribution/oneStar', 'reviewsDistribution/threeStar',
       'reviewsDistribution/twoStar', 'scrapedAt', 'searchPageUrl',
       'searchString', 'state', 'street', 'subTitle', 'temporarilyClosed',
       'title', 'totalScore', 'url', 'website'],
      dtype='object')

useful features:

- delivery distan
- Location  
- Price  
- Hours of service (currently Closed or Open)
- Food they serve (food category)
- Reviews 
- Diversity of food 
- Revenue (maybe)
- Weather conditions based on location
- Delivery distance
- Rate (mean, median scores) 
-